trigger:
  batch: true
  branches:
    include:
    - release/3.*
    - internal/release/3.*

pr: none

schedules:
- cron: "0 13 * * *"
  displayName: Mon through Sun at 5:00 AM (UTC-8:00)
  branches:
    include:
    - master
  always: true
- cron: "0 1 * * *"
  displayName: Mon through Sun at 5:00 PM (UTC-8:00)
  branches:
    include:
    - master
  always: true

variables:
- name: _DotNetArtifactsCategory
  value: CORECLR
- name: CrossDacCoreClrVersion
  value: ''

stages:
  - stage: Prepare
    jobs:
    #
    # Cross-dac prepare
    #
    - template: /eng/platform-matrix.yml
      parameters:
        jobTemplate: build-crossdac-job.yml
        buildConfig: release
        platforms:
        - Linux_musl_x64 # Choose the lightest weight linux platform

  - stage: Build
    jobs:
    #
    # Cross-dac build
    #
    - template: /eng/platform-matrix.yml
      parameters:
        jobTemplate: build-crossdac-job.yml
        buildConfig: release
        dependsOn:
        - build_Linux_musl_x64_release
        platforms:
        - Windows_NT_arm
        - Windows_NT_arm64
        - Windows_NT_x64
        jobParameters:
          # Publishing packages to blob feeds sometimes takes a long time
          # due to waiting for an exclusive lock on the feed.
          # See https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing.md
          timeoutInMinutes: 120
          coreClrBuildId: variables['coreClrVersion']

    #
    # Publish build information to Build Assets Registry
    #
    # This job gathers build assets from the pipeline (from each official
    # product build job), and publishes them to the build assets
    # registry. Its dependencies should be updated to include all of the
    # official builds if we add more platform/arch combinations.
    - template: /eng/finalize-publish.yml
      parameters:
        dependsOn:
        - build_Windows_NT_x64_release
        - build_Windows_NT_arm_release
        - build_Windows_NT_arm64_release
